[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --production=false --legacy-peer-deps || true"]

[phases.build]
cmds = ["echo 'Build skipped'"]

[start]
cmd = "npx tsx server/index.ts"

[variables]
NODE_ENV = "production"