[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --production=false --legacy-peer-deps"]

[phases.build]
cmds = ["npx vite build"]

[start]
cmd = "npx tsx server/index.ts"

[variables]
NODE_ENV = "production"