[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --production=false --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build:railway"]

[start]
cmd = "npm run start:railway"

[variables]
NODE_ENV = "production"